steps:
  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-frontend:latest'
      - '-f'
      - 'cloudrun/frontend.Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=${_BACKEND_URL}'
      - '.'

  # Push the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-frontend:latest'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-frontend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
