steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-backend:latest'
      - '-f'
      - 'cloudrun/backend.Dockerfile'
      - '.'

  # Push the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-backend:latest'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/nexus-repo/nexus-backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
